[project]
name = "advanced_login_system"
version = "0.1.0"
description = ""
authors = [
    {name = "Luan Kaike",email = "luankaikemacksantos@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mysql-connector-python (>=26.7.0,<27.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "flask (>=3.1.3,<4.0.0)",
    "customtkinter (>=6.0.0,<7.0.0)",
    "requests (>=2.34.2,<3.0.0)"
]

[tool.poetry]
packages = [
	{include = "als_db", from = "src"},
	{include = "als_api", from = "src"},
	{include = "als_client", from = "src"},
	{include = "als_request", from = "src"},
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
