DROP TABLE IF EXIST users;

CREATE TABLE users (
	user_id int PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	tel VARCHAR(11) UNIQUE,
	can_view_user_table BOOL DEFAULT FALSE,
	can_create_new_user BOOL DEFAULT FALSE
)